CREATE TABLE Comment (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Comment NVARCHAR(MAX) NOT NULL,
	TaskId UNIQUEIDENTIFIER NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	UpdatedAt DATETIME NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL,
	FOREIGN KEY (TaskId) REFERENCES Task(Id),
	FOREIGN KEY (CreatedBy) REFERENCES [User](Id),
	FOREIGN KEY (UpdatedBy) REFERENCES [User](Id)
)