CREATE TABLE ProjectMember (
	UserId UNIQUEIDENTIFIER NOT NULL,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY (UserId, ProjectId),
	RoleId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (ProjectId) REFERENCES Project(Id),
	FOREIGN KEY (RoleId) REFERENCES Role(Id),
)