CREATE TABLE UserProject (
	UserId UNIQUEIDENTIFIER NOT NULL,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY (UserId, ProjectId),
	RoleId UNIQUEIDENTIFIER NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	UpdatedAt DATETIME NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (ProjectId) REFERENCES Project(Id),
	FOREIGN KEY (RoleId) REFERENCES Role(Id),
	FOREIGN KEY (CreatedBy) REFERENCES [User](Id),
	FOREIGN KEY (UpdatedBy) REFERENCES [User](Id)
)