CREATE TABLE Comment (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Comment NVARCHAR(255) NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	TaskId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (TaskId) REFERENCES Task(Id)
)