CREATE TABLE TemplateState
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Color NVARCHAR(7) NOT NULL DEFAULT '#6c757d',
    SortOrder INT NOT NULL DEFAULT 0,
    TemplateId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (TemplateId) REFERENCES Template(Id)
);