CREATE TABLE [State] (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(255),
    Color NVARCHAR(7) NOT NULL DEFAULT '#6c757d',
	SortOrder INT NOT NULL,
    ProjectId UNIQUEIDENTIFIER NOT NULL,
	CreatedAt DATETIME NULL DEFAULT GETDATE(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL,
	FOREIGN KEY (CreatedBy) REFERENCES [User](Id),
	FOREIGN KEY (UpdatedBy) REFERENCES [User](Id),
	FOREIGN KEY (ProjectId) REFERENCES [Project](Id) ON DELETE CASCADE
)