CREATE TABLE Tag
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [Name] nvarchar(50) NOT NULL,
    Color nvarchar(7) NOT NULL,
    SortOrder int NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	UpdatedAt DATETIME NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL,
    ProjectId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (ProjectId) REFERENCES Project(Id)
);