CREATE TABLE Task (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(255) NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	StatusId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (ProjectId) REFERENCES Project(Id),
	FOREIGN KEY (StatusId) REFERENCES [Status](Id)
)