CREATE TABLE TemplateTag
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Color NVARCHAR(7) NOT NULL DEFAULT '#6c757d',
    SortOrder INT NOT NULL,
    TemplateId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (TemplateId) REFERENCES Template(Id)
)