CREATE TABLE Project (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(255),
    StartDate DATETIME NULL,
    EndDate DATETIME NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	UpdatedAt DATETIME NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL,

	FOREIGN KEY (CreatedBy) REFERENCES [User](Id),
	FOREIGN KEY (UpdatedBy) REFERENCES [User](Id),

    CONSTRAINT CHK_Project_EndDate_After_StartDate
    CHECK (EndDate >= StartDate)
)