CREATE TABLE Project (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(255),
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	UpdatedAt DATETIME NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL,
	FOREIGN KEY (CreatedBy) REFERENCES [User](Id),
	FOREIGN KEY (UpdatedBy) REFERENCES [User](Id)
)