CREATE TABLE UserProject (
	UserId UNIQUEIDENTIFIER NOT NULL,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY (UserId, ProjectId),
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (ProjectId) REFERENCES Project(Id)
)