CREATE TABLE UserTask (
	UserId UNIQUEIDENTIFIER NOT NULL,
	TaskId UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY (UserId, TaskId),
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (TaskId) REFERENCES Task(Id)
)