CREATE TABLE [State] (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Number INT NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(255),
    ProjectId UNIQUEIDENTIFIER NOT NULL,
	CreatedAt DATETIME NULL DEFAULT GETDATE(),
	CreatedBy UNIQUEIDENTIFIER NULL,
	UpdatedAt DATETIME NULL,
	UpdatedBy UNIQUEIDENTIFIER NULL,
	FOREIGN KEY (CreatedBy) REFERENCES [User](Id),
	FOREIGN KEY (UpdatedBy) REFERENCES [User](Id),
	FOREIGN KEY (ProjectId) REFERENCES [Project](Id)
)