CREATE TABLE Task (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(255),
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NULL,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	StateId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (ProjectId) REFERENCES Project(Id),
	FOREIGN KEY (StateId) REFERENCES [State](Id)
)